title: Snap
email: robertpayne@me.com
description: Swift AutoLayout DSL for iOS and OS X
baseurl: "/Snap"
url: "http://masonry.github.io/"
twitter_username: robertjpayne
github_username:  robertjpayne

markdown: kramdown
