title: Snap
email: robertpayne@me.com
description: Swift AutoLayout DSL for iOS and OS X
url: "http://www.snapkit.io/"
twitter_username: robertjpayne
github_username:  robertjpayne

markdown: kramdown
